#file-save-path: E:/workspace/IDEA_workspace/myBlog/dist/uploads/
file-save-path: /var/www/html/dist/uploads/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myBlog?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
#    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  web:
    resources:
      static-locations: classpath:/static

server:
  port: 8089
  servlet:
    context-path: /blog


mybatis:
  mapper-locations: classpath:mapper/*.xml

